services:
  - type: web
    name: django-medical-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir backend myproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
