# Generated by Django 6.0.1 on 2026-02-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
